#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Nexus.OAuth.Android.Resource", IsApplication=true)]

namespace Nexus.OAuth.Android
{
	
	
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "13.2.0.93")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Animation
		{
			
			// aapt resource value: 0x7F010000
			public const int anim_fluid_account = 2130771968;
			
			// aapt resource value: 0x7F010001
			public const int card_slide_in_bottom = 2130771969;
			
			// aapt resource value: 0x7F010002
			public const int card_slide_out_bottom = 2130771970;
			
			// aapt resource value: 0x7F010003
			public const int fragment_slide_in_left = 2130771971;
			
			// aapt resource value: 0x7F010004
			public const int fragment_slide_in_right = 2130771972;
			
			// aapt resource value: 0x7F010005
			public const int fragment_slide_out_left = 2130771973;
			
			// aapt resource value: 0x7F010006
			public const int fragment_slide_out_right = 2130771974;
			
			static Animation()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Animation()
			{
			}
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7F020000
			public const int colorAccent = 2130837504;
			
			// aapt resource value: 0x7F020001
			public const int colorPrimary = 2130837505;
			
			// aapt resource value: 0x7F020002
			public const int colorPrimaryDark = 2130837506;
			
			// aapt resource value: 0x7F020003
			public const int ic_launcher_background = 2130837507;
			
			// aapt resource value: 0x7F020004
			public const int transparent = 2130837508;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7F030000
			public const int button_text_size = 2130903040;
			
			// aapt resource value: 0x7F030001
			public const int card_padding = 2130903041;
			
			// aapt resource value: 0x7F030002
			public const int default_elevation = 2130903042;
			
			// aapt resource value: 0x7F030003
			public const int input_text_margin = 2130903043;
			
			// aapt resource value: 0x7F030004
			public const int input_text_width = 2130903044;
			
			// aapt resource value: 0x7F030005
			public const int margin_top_header = 2130903045;
			
			// aapt resource value: 0x7F030006
			public const int progress_length = 2130903046;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7F040000
			public const int circle_gradient = 2130968576;
			
			// aapt resource value: 0x7F040001
			public const int circle_shape = 2130968577;
			
			// aapt resource value: 0x7F040002
			public const int circular_progress_bar = 2130968578;
			
			// aapt resource value: 0x7F040003
			public const int crystal_contour = 2130968579;
			
			// aapt resource value: 0x7F040004
			public const int ic_person = 2130968580;
			
			// aapt resource value: 0x7F040005
			public const int left_arrow = 2130968581;
			
			// aapt resource value: 0x7F040006
			public const int nexus_crystal = 2130968582;
			
			// aapt resource value: 0x7F040007
			public const int question = 2130968583;
			
			// aapt resource value: 0x7F040008
			public const int ripple_normal = 2130968584;
			
			// aapt resource value: 0x7F040009
			public const int settings = 2130968585;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Font
		{
			
			// aapt resource value: 0x7F050000
			public const int comfortaa = 2131034112;
			
			static Font()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Font()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7F060000
			public const int bgLoading = 2131099648;
			
			// aapt resource value: 0x7F060001
			public const int btnAuthorize = 2131099649;
			
			// aapt resource value: 0x7F060002
			public const int btnCreateAccount = 2131099650;
			
			// aapt resource value: 0x7F060003
			public const int btnDecline = 2131099651;
			
			// aapt resource value: 0x7F060004
			public const int btnForgotPassword = 2131099652;
			
			// aapt resource value: 0x7F060005
			public const int btnLogout = 2131099653;
			
			// aapt resource value: 0x7F060006
			public const int btnNext = 2131099654;
			
			// aapt resource value: 0x7F060007
			public const int cardApplication = 2131099655;
			
			// aapt resource value: 0x7F060008
			public const int cardLoading = 2131099656;
			
			// aapt resource value: 0x7F060009
			public const int cardProfileImage = 2131099657;
			
			// aapt resource value: 0x7F06000A
			public const int cbShowPassword = 2131099658;
			
			// aapt resource value: 0x7F06000B
			public const int edtLogin = 2131099659;
			
			// aapt resource value: 0x7F06000C
			public const int edtPassword = 2131099660;
			
			// aapt resource value: 0x7F06000D
			public const int fgDialog = 2131099661;
			
			// aapt resource value: 0x7F06000E
			public const int imgCameraOutPut = 2131099662;
			
			// aapt resource value: 0x7F06000F
			public const int imgLiquid = 2131099663;
			
			// aapt resource value: 0x7F060010
			public const int imgLogo = 2131099664;
			
			// aapt resource value: 0x7F060011
			public const int imgProfileImage = 2131099665;
			
			// aapt resource value: 0x7F060012
			public const int iptPassword = 2131099666;
			
			// aapt resource value: 0x7F060013
			public const int iptUser = 2131099667;
			
			// aapt resource value: 0x7F060014
			public const int ltBackground = 2131099668;
			
			// aapt resource value: 0x7F060015
			public const int ltHeader = 2131099669;
			
			// aapt resource value: 0x7F060016
			public const int mask = 2131099670;
			
			// aapt resource value: 0x7F060017
			public const int progressBar = 2131099671;
			
			// aapt resource value: 0x7F060018
			public const int rcvInfos = 2131099672;
			
			// aapt resource value: 0x7F060019
			public const int txtDescription = 2131099673;
			
			// aapt resource value: 0x7F06001A
			public const int txtEmail = 2131099674;
			
			// aapt resource value: 0x7F06001B
			public const int txtItemKey = 2131099675;
			
			// aapt resource value: 0x7F06001C
			public const int txtItemValue = 2131099676;
			
			// aapt resource value: 0x7F06001D
			public const int txtName = 2131099677;
			
			// aapt resource value: 0x7F06001E
			public const int txtReadMore = 2131099678;
			
			// aapt resource value: 0x7F06001F
			public const int txtUser = 2131099679;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Integer
		{
			
			// aapt resource value: 0x7F070000
			public const int fragment_slid_duration = 2131165184;
			
			// aapt resource value: 0x7F070001
			public const int max_email_characters = 2131165185;
			
			// aapt resource value: 0x7F070002
			public const int max_password_characters = 2131165186;
			
			static Integer()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Integer()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7F080000
			public const int activity_account = 2131230720;
			
			// aapt resource value: 0x7F080001
			public const int activity_authorize = 2131230721;
			
			// aapt resource value: 0x7F080002
			public const int activity_login = 2131230722;
			
			// aapt resource value: 0x7F080003
			public const int activity_qrcode = 2131230723;
			
			// aapt resource value: 0x7F080004
			public const int content_loading = 2131230724;
			
			// aapt resource value: 0x7F080005
			public const int dialog_loading_task = 2131230725;
			
			// aapt resource value: 0x7F080006
			public const int fragment_authorize = 2131230726;
			
			// aapt resource value: 0x7F080007
			public const int fragment_login_first_step = 2131230727;
			
			// aapt resource value: 0x7F080008
			public const int fragment_login_second_step = 2131230728;
			
			// aapt resource value: 0x7F080009
			public const int item_account_info = 2131230729;
			
			// aapt resource value: 0x7F08000A
			public const int item_account_info_disabled = 2131230730;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Mipmap
		{
			
			// aapt resource value: 0x7F090000
			public const int ic_launcher = 2131296256;
			
			// aapt resource value: 0x7F090001
			public const int ic_launcher_adaptive_fore = 2131296257;
			
			// aapt resource value: 0x7F090002
			public const int ic_launcher_round = 2131296258;
			
			static Mipmap()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Mipmap()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7F0A0000
			public const int action_settings = 2131361792;
			
			// aapt resource value: 0x7F0A0001
			public const int app_name = 2131361793;
			
			// aapt resource value: 0x7F0A0002
			public const int btn_authorize = 2131361794;
			
			// aapt resource value: 0x7F0A0003
			public const int btn_create_account = 2131361795;
			
			// aapt resource value: 0x7F0A0004
			public const int btn_decline = 2131361796;
			
			// aapt resource value: 0x7F0A0005
			public const int btn_forgot_password = 2131361797;
			
			// aapt resource value: 0x7F0A0006
			public const int btn_logout = 2131361798;
			
			// aapt resource value: 0x7F0A0007
			public const int btn_next = 2131361799;
			
			// aapt resource value: 0x7F0A0008
			public const int error_invalid_password = 2131361800;
			
			// aapt resource value: 0x7F0A0009
			public const int error_invalid_user = 2131361801;
			
			// aapt resource value: 0x7F0A000A
			public const int error_null = 2131361802;
			
			// aapt resource value: 0x7F0A000B
			public const int error_null_user = 2131361803;
			
			// aapt resource value: 0x7F0A000C
			public const int helper_text_password = 2131361804;
			
			// aapt resource value: 0x7F0A000D
			public const int helper_text_user = 2131361805;
			
			// aapt resource value: 0x7F0A000E
			public const int hint_password = 2131361806;
			
			// aapt resource value: 0x7F0A000F
			public const int hint_show_password = 2131361807;
			
			// aapt resource value: 0x7F0A0010
			public const int hint_user = 2131361808;
			
			// aapt resource value: 0x7F0A0011
			public const int info_created = 2131361809;
			
			// aapt resource value: 0x7F0A0012
			public const int info_culture = 2131361810;
			
			// aapt resource value: 0x7F0A0013
			public const int info_date_of_birth = 2131361811;
			
			// aapt resource value: 0x7F0A0014
			public const int info_email = 2131361812;
			
			// aapt resource value: 0x7F0A0015
			public const int info_name = 2131361813;
			
			// aapt resource value: 0x7F0A0016
			public const int info_phone = 2131361814;
			
			// aapt resource value: 0x7F0A0017
			public const int text_application_not_found = 2131361815;
			
			// aapt resource value: 0x7F0A0018
			public const int text_header_login = 2131361816;
			
			// aapt resource value: 0x7F0A0019
			public const int text_header_password = 2131361817;
			
			// aapt resource value: 0x7F0A001A
			public const int text_header_user = 2131361818;
			
			// aapt resource value: 0x7F0A001B
			public const int text_read_more = 2131361819;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7F0B0000
			public const int AppTheme = 2131427328;
			
			// aapt resource value: 0x7F0B0001
			public const int AppTheme_Button = 2131427329;
			
			// aapt resource value: 0x7F0B0002
			public const int AppTheme_Button_TextButton = 2131427330;
			
			// aapt resource value: 0x7F0B0003
			public const int AppTheme_Dialog_FullScreen = 2131427331;
			
			// aapt resource value: 0x7F0B0004
			public const int AppTheme_NoActionBar = 2131427332;
			
			// aapt resource value: 0x7F0B0005
			public const int AppTheme_Translucent = 2131427333;
			
			// aapt resource value: 0x7F0B0006
			public const int TextViewStyle = 2131427334;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
